### ISSUE TITLE
problem with iframe set to 0px

### ISSUE THREAD

**Issue by jbgaya** [BugzTheBunny/streamlit-navbar-flaskless#2]
Hi, 

Thanks for this nice tool ! 

I saw that you  [disabled iframes in the css file](https://github.com/BugzTheBunny/streamlit-navbar-flaskless/blob/main/assets/styles.css#L97-L99) to avoid a block below the navigation bar. I personally need iframes in the app I am creating. 

Do you have any workaround to both delete this empty block and enable other iframes ? 

Thanks !

**Comment by BugzTheBunny** [comment]
Hi @jbgaya , Sorry for the late response.
Yes I do, you can use specific iframes and set their properties.
For example in the app I'm developing, the only IFRAME I need, comes from 'streamlit-tags' component.
So I did this in the CSS file:

```
iframe{
    height: 0rem;
}

iframe[title="streamlit_tags.streamlit_tags"]{
    height: 100%;
}
```

This is kind of a dirty workaround, but it work for me for now.
